### PR TITLE
Only derive variables if not explicitly defined

### PR DESCRIPTION
**Pull request by cpavanrun**
Because of GDPR consideration we mask day of the exact day of birth (all set to 01). Hence, the derivation of the age of first diagnosis is inaccurate in some cases.

We now calculate age of first diagnosis upstream and push this to the pipelines. However, even if defined, the age of diagnosis was still being derived.

Hence, this PR changes this. If the derivative is already defined, it will not be overwritten.

### CODE REVIEW

**Comment by gijskant** [comment]
Okay, I understand the need. It does involve a little bit more, because this behaviour was considered to be suspicious: overriding a field that is specified as a derived value.
In this case, the validation in [sources_reader.py:151](https://github.com/thehyve/python_csr2transmart/blob/master/sources2csr/sources_reader.py#L151) should be removed, otherwise the pipeline will fail.
Could you add that change?

**Comment by gijskant** [comment]
And the test in [test_sources2csr.py:133](https://github.com/thehyve/python_csr2transmart/blob/master/tests/sources2csr/test_sources2csr.py#L133) plus related test data directory?

**Review by gijskant — CHANGES_REQUESTED** [review]
Please remove the validation that prevents derived values to be read from source files directly.

**Comment by cpavanrun** [comment]
Thank you for checking GijsI will jump right on it!

**Comment by gijskant** [comment]
1. I have an alternative idea: instead of removing the validation, remove the `derived` flag from the data model: [csr.py:25-26](https://github.com/thehyve/python_csr2transmart/blob/master/csr/csr.py#L25). There are other fields that are derived as well.

**Comment by gijskant** [comment]
2. Could you rebase your changes on `master`? The git history is becoming a mess like this.

**Comment by gijskant** [comment]
@cpavanrun Does this alternative implementation suit your needs: #66 ?

**Comment by cpavanrun** [comment]
> @cpavanrun Does this alternative implementation suit your needs: #66 ?

Yes it will! I will close this PR.

**Pull request closed without merging**
