### PR TITLE
Datamodel change library_strategy analysis_type

### PR DESCRIPTION
**Pull request by ShashiPMC**
### What has changed?
Addition of NGS data to CSR was already a concept in the sources2csr.py code, however it was never fully implemented.
This PR changes the way NGS data is added by making it no longer be a derived value but an optional source value.
In the future, NGS data will be added with a script directly in the drop_zone. 

This PR also includes a (Py)test to check if there is a mismatch in molecule type of a biomaterial and the library strategy applied to that biomaterial. For instance: RNA data should never have WXS or WGS library strategies applied to it.

Other than code changes, the ontology_config.json and source_config.json files also need to be altered to allow reading in the new source data and displaying it on CSR.

### Why was this change needed?
We wish to include library_strategy and analysis_type in CSR to allow researchers to shop for data effectively. In the past researchers using CSR requested data for many biomaterials which are not available in our systems. Having data availability in CSR will improve this aspect.

### CODE REVIEW

**Comment by gijskant** [comment]
Thank you for the clear description, the proposed changes and the good test coverage! I will provide some on how to improve the changes further.
1. The validation of the consistency of `type` and `library_strategy` can be moved to `csr.py`, to make it explicitly part of the data model as a validator, similar to other validators. Adding the following to the `Biomaterial` class would work:
    ```python
    @validator('library_strategy')
    def validate_molecule_type_agrees_with_library_strategy(cls, library_strategy, values):
        if 'type' in values and library_strategy is not None:
            if values['type'] == 'DNA' and library_strategy.__contains__('RNA-Seq'):
                raise DataException(f'Not allowed RNA-Seq library strategy for molecule type: DNA')
            if values['type'] == 'RNA' and library_strategy.__contains__('WXS'):
                raise DataException(f'Not allowed WXS library strategy for molecule type: RNA')
            if values['type'] == 'RNA' and library_strategy.__contains__('WGS'):
                raise DataException(f'Not allowed WGS library strategy for molecule type: RNA')
            if values['type'] == 'RNA' and library_strategy.__contains__('DNA-meth_array'):
                raise DataException(f'Not allowed DNA-meth_array library strategy for molecule type: RNA')
    ```
    You would have to change the expected error in the test. The library strategy error message is written to the console log, but 'Invalid data for Biomaterial with id BM2' will be in the error generated by `sources2csr`.
    To get some more meaningful feedback on an error (not exactly line numbers, but at least including identifier of the mismatched biomaterial), you could change the error logging in `transform_entities` in https://github.com/thehyve/python_csr2transmart/blob/0807ca4c63007ad47bb0f4af3d97d60d15e20c96/sources2csr/sources_reader.py#L53:
    ```python
    try:
        result.append(constructor(entity))
    except Exception as e:
        entity_name = schema['title']
        id = entity[id_property]
        message = f'Invalid data for {entity_name} with id {id}'
        logger.error(message)
        logger.error(e)
        raise DataException(message)
    ```
 2. Now that the `add_ngs_data` function has been commented out, we may as well remove the functions for the derived ngs values altogether, i.e., removing ngs2csr.py, ngs_maf_reader.py, ngs_reader.py, ngs_seg_reader.py, ngs_txt_reader.py and test_ngs2csr.py. That code would be unused anyway and if we want to reuse any of it, it is still there in the git history.

**Comment by gijskant** [comment]
Please also include a test that checks if splitting by `;` is applied correctly. You can add multiple values (separated by `;`) in an existing test data file (e.g., test_data/input_data/CLINICAL/biomaterial_with_derived_values.tsv, which you may want to rename). And then extend and existing test in `test_sources2csr.py` to check if all values were correctly read.

**Comment by ShashiPMC** [comment]
Hello Gijs,

Thanks for reviewing and giving great tips!
I have applied your suggestions and pushed them over.
Please let me know if anything else can be improved.

One question I do have: why is the pipeline erroring if there is already a individual.tsv file in the working directory instead of just overwriting?
Is this intended behaviour?

Regards,

Shashi Badloe

**Comment by gijskant** [comment]
> One question I do have: why is the pipeline erroring if there is already a individual.tsv file in the working directory instead of just overwriting?
> Is this intended behaviour?

This is indeed intended behaviour to prevent a pipeline from accidentally overwriting existing data. This leaves tools that use the script (and the transmart_loader package) with two options: 1. create a fresh target directory for every run; or 2. clear the target directory before every run.
It can indeed be annoying when debugging and I have considered removing this behaviour. But sofar I prefer the safety of not overwriting existing data. We could make this configurable, which would require changes in https://github.com/thehyve/python_csr2transmart/blob/master/csr/entity_writer.py#L37 and https://github.com/thehyve/python_transmart_loader/blob/master/transmart_loader/tsv_writer.py#L23.

**Review by gijskant — APPROVED** [review]
Looks good, great work!

**Comment by ShashiPMC** [comment]
Thanks!

I did not change any version numbers. Is this required?

**Comment by gijskant** [comment]
> I did not change any version numbers. Is this required?
No, I am creating a new release now (`0.1.0`).

**Pull request merged**
